install:
    - pip install travis-sphinx
    - pip install sphinx_rtd_theme
language: python
python:
    - 3.6
script:
    - travis-sphinx --outdir='docs/_build' build --source=docs/source --nowarn
deploy:
    - provider: pages
      skip_cleanup: true
      github_token: 53f862a5691be9005c891242c4ac5ef8438498a2
      local_dir: docs/_build
      on:
        branch: master
        python: 3.6
